### PR TITLE
Labs 8281 & 7721

### PR DESCRIPTION
**Pull request by SimonWeisserOracle**
Made requested changes to lab. Resolved conflicts between branches

### CODE REVIEW

**Review by rfontcha — CHANGES_REQUESTED** [review]
@SimonWeisserOracle - All file names must be in lowercase. No Upper or Mixed case. Please revert all the changes that are renaming file extensions to UPPERCASE

**Review by rfontcha — CHANGES_REQUESTED** [review]
@SimonWeisserOracle  - Your pull request is renaming plenty of files from the required lowercase spelling  to either mixed case or Uppercase extension. Please revert all those changes.

image

**Comment by SimonWeisserOracle** [comment]
I have no idea why this happened, as I did not do this myself. I am also not sure how to revert these changes. Could someone from the livelabs team please reach out to me to set up a meeting and go over this. I have been going back and forth for months on issues not even relating to my own lab but for merge requests.

**Comment by rfontcha** [comment]
@SimonWeisserOracle  - Closing as per our conversation. Please re-clone and your repo and resubmit

**Pull request closed without merging**
