### PR TITLE
WMS ID: 11020 - Pull request created to meet the new self-QA checklist requirements

### PR DESCRIPTION
**Pull request by yutakats**
WMS ID: 11020 - Pull request created for the last minute corrections to comply the new self-QA checklist.

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
This branch has conflicts that must be resolved

**Comment by yutakats** [comment]
I resolved the the conflicts manually. Not sure why it happened..

**Review by arabellayao — CHANGES_REQUESTED** [review]
Could you please change the “help” email in the two manifest.json files to “livelabs-help-em_us_grp@oracle.com”? I think that is the workshop’s stakeholder email. Everything else looks good. Thank you!

**Comment by yutakats** [comment]
Thank you - I have made the changes to the help emails in my local files and pushed to the master. Do i have to create another Pull request..?

**Review by malcherm — APPROVED** [review]

**Pull request merged**
