### PR TITLE
Update docs to reflect latest script and terraform changes

### PR DESCRIPTION
**Pull request by recursivecodes**

### CODE REVIEW

**Comment by graemerocher** [comment]
Approved

**Review by tmcginn — DISMISSED** [review]

**Comment by graemerocher** [comment]
Actually appears there are conflicts, @recursivecodes could you fix those?

**Comment by recursivecodes** [comment]
@graemerocher done!

**Comment by graemerocher** [comment]
@kaymalcolm @tmcginn this is ready to merge.

Thanks @recursivecodes !

**Review by tmcginn — APPROVED** [review]

**Pull request merged**
