### PR TITLE
11066: Column Mapping and Purging Data in Oracle GoldenGate Veridata Workshop

### PR DESCRIPTION
**Pull request by achepuri**
Hi,
Could you please publish the "11066: Column Mapping and Purging Data in Oracle GoldenGate Veridata" Workshop.
github pages: https://achepuri.github.io/learning-library/data-management-library/goldengate/veridata/workshops/freetier-tools/?lab=intro-tools

Thanks,
Anu

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
hi, please follow the QA checklist document for image and file naming conventions, 
 
1.4. Image filenames should be descriptive, not step numbers, or autogenerated names

and there should be Alt text on what the image is, this is required from an accessibility perspective. 


image

**Comment by madhusudhanrao-ppm** [comment]
image names should be all lower case if required use - in between words for example, create-table.png or createtable.png and do not use _ or capital letters for image names, please refer QA checklist document for file naming conventions

**Review by rfontcha — CHANGES_REQUESTED** [review]
@achepuri - All paths and file names must be in lowercase format. Please rename accordingly, commit, and push. 
image


Proceed as detailed below:

--------------

Using a terminal emulator on your computer (e.g. Git Bash, MobaXterm on windows) or MacOS terminal, navigate to the parent directory of your workshop and run any of the following to rename UPPER/Mixed cases to lower
e.g. 

cd /drives/c/learning-library/security-library/myworkshop

#Look for files only blindly convert to lowercase
for f in *; do if [ ! -d "$f" ]; then git mv -k "$f" "$(echo $f | tr "[:upper:]" "[:lower:]")"; fi done

#Look for files (recursive) in the directory/folder and subsequent subdirs with any UPPERCASE character and rename to lowercase
for f in `find | egrep '[A-Z]+$'`; do git mv "$f" "`echo $f | tr "[:upper:]" "[:lower:]"`"; done

---------------------

**Comment by madhusudhanrao-ppm** [comment]
please give descriptive image names and refer QA checklist document. Image names should not have Capital letters or _ underscores, you can attend one of our office hours to know more about QA checklist requirements 

image

image

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Review by madhusudhanrao-ppm — DISMISSED** [review]

**Review by rfontcha — CHANGES_REQUESTED** [review]
@achepuri  - Please rename this as well
image

**Review by rfontcha — CHANGES_REQUESTED** [review]
@achepuri - Your manifests are incorrect. Please follow the example from "**_../sample-livelabs-templates/sample-workshop-novnc/workshops_**" to properly update your 3 folders:

- desktop-tools
- freetier-tools
- livelabs-tools

Also revert the changes you made to the manifest files under **_desktop, freetier_**, and **_livelabs_**. The changes you made are erroneous and will impact existing workshop if merged.

**Review by rfontcha — APPROVED** [review]

**Review by davidastart — APPROVED** [review]

**Pull request merged**
