### PR TITLE
converge-db-for-developers

### PR DESCRIPTION
**Pull request by nishakau**
This is a completely new Converged Database Workshop lab and is intended for Java developers.

### CODE REVIEW

**Review by kaymalcolm — CHANGES_REQUESTED** [review]
This is a big change to a workshop already in production.  Who authorized this update?

**Review by rfontcha — CHANGES_REQUESTED** [review]
I see plenty of redundancy between this workshop and the "converged-db-on-premises" that's is currently in production. Please review  and provide justifications as to why both are needed on LiveLabs.

**Comment by nishakau** [comment]
@rfontcha, This is a completely new lab created for converged database and the purpose of this lab differs form the Converged database lab that we have in production right now.

The lab is supposed to reside at "/learning-library/developer-library/converged-db/converged-db-for-developers" .

This pull request don't include changes for any other workshop labs, the pull request is supposed to create its own place at the above mentioned location in learning library.

**Review by rfontcha — CHANGES_REQUESTED** [review]
Please rename as per our discussion today and resubmit

Thanks,
Rene

**Comment by rfontcha** [comment]
Please rename as per our discussion today and resubmit

Thanks,
Rene

**Pull request closed without merging**
