### PR TITLE
Adding new workshop

### PR DESCRIPTION
**Pull request by shlayel**
A new workshop is added under APEX.

### CODE REVIEW

**Review by tmcginn — COMMENTED** [review]
@shlayel - Do you have a WMS (http://bit.ly/oraclewms) entry created for this workshop? If yes, please add the WMS ID to the pull request. If no, please create the WMS entry first and add the WMS id here. Thanks

**Comment by shlayel** [comment]
> @shlayel - Do you have a WMS (http://bit.ly/oraclewms) entry created for this workshop? If yes, please add the WMS ID to the pull request. If no, please create the WMS entry first and add the WMS id here. Thanks

The WMS ID is 7081

**Review by tmcginn — APPROVED** [review]
Thanks @shlayel

**Comment by tmcginn** [comment]
Next step is self-QA

**Pull request merged**
