### PR TITLE
images fixed

### PR DESCRIPTION
**Pull request by Mmm-Biscuits**
fixed a few images that we referenced incorrectly.

### CODE REVIEW

**Review by anooshapilli — APPROVED** [review]

**Comment by anooshapilli** [comment]
@Mmm-Biscuits , Please resolve the conflicts.

**Review by rfontcha — CHANGES_REQUESTED** [review]
You have a conflict. Please resolve it first

**Review by tmcginn — APPROVED** [review]

**Comment by tmcginn** [comment]
@Mmm-Biscuits - Brian, have you resolved these conflicts?

**Comment by Mmm-Biscuits** [comment]
yes

**Review by rfontcha — APPROVED** [review]

**Pull request merged**
