### PR TITLE
Pull request to update all the .md files in the tomcat-to-oci tutorial WMS ID 2680

### PR DESCRIPTION
**Pull request by smanna202**
@streamnsight - This pull request includes the outstanding edits I implemented as a part of the OHC Learn Publishing Team.
https://github.com/smanna202/learning-library/tree/master/developer-library/tomcat-to-oci

### CODE REVIEW

**Review by tmcginn — CHANGES_REQUESTED** [review]
@smanna202 - I thought we agreed to replace STEP with Task, rather than simply remove STEP altogether? I am going to replace STEP with Task globally tomorrow....

**Comment by smanna202** [comment]
@tmcginn sorry, my mistake. I saw the prefix was removed in the other strategic solutions tutorials so I followed suite. I'll add it back now.

**Comment by smanna202** [comment]
@tmcginn STEP prefix is back in! Thanks!

**Review by tmcginn — COMMENTED** [review]
Thanks @smanna202 !

**Review by tmcginn — APPROVED** [review]

**Pull request merged**
