### PR TITLE
LWS 4121 and 4801: changes to include federated login for always-free workshops

### PR DESCRIPTION
**Pull request by sherylmanoharan**

### CODE REVIEW

**Comment by sherylmanoharan** [comment]
The cloud-login/pre-register-free-tier-account.md file has been updated based on user feedback that it takes between 10-30 minutes for an account to be provisioned and that logging out and logging in works better, as the navigation menu sometimes doesn't show up when you stay signed in.

**Comment by anooshapilli** [comment]
@sherylmanoharan  Could you share the workshop ID ?

**Comment by sherylmanoharan** [comment]
Apologies, @anooshapilli LWS 4121 and 4801. Will update the PR as well.

**Review by kaymalcolm — COMMENTED** [review]
Sheryl, this is changing the free tier sign up process.  @kamryn-v can you go through these steps and verify this is correct?  If you approve then I will proceed and approve. (Sheryl this affects 200+ workshops so we have to triple check these steps to make sure they are accurate).

**Comment by sherylmanoharan** [comment]
@kaymalcolm I checked with Tom before making the changes, but yes, will wait to make sure things check out.

**Review by kaymalcolm — APPROVED** [review]
Approved. Sheryl checked with @tmcginn before making the freetier updates.

**Pull request merged**
