### PR TITLE
ID#6021 - Unified Observability and ID#8781 - Sagas  doc work

### PR DESCRIPTION
**Pull request by paulparkinson**
ID#6021 - Unified Observability in Grafana with converged Oracle Database
ID#8781 - Sagas

### CODE REVIEW

**Comment by anooshapilli** [comment]
@paulparkinson - Please fill the QA checklist form and mail it to us - livelabs-help-db_us@oracle.com. Then we will review the workshop and approve the PR if everything looks good and start working on moving the workshop to production.
Thanks!
Anoosha

**Comment by paulparkinson** [comment]
Thanks @anooshapilli   Sorry to ask but can you point me to the QA checklist form?

**Comment by paulparkinson** [comment]
@anooshapilli  
QA checklist email sent for  ID#6021 - "Unified Observability in Grafana with converged Oracle Database" This has been tested and ready for publish review/approval.
ID#8781 - "Sagas" is still being worked on (should be ready in the next few days)

**Comment by anooshapilli** [comment]
@paulparkinson - Thanks for the QA checklist email. Please fill the QA checklist form mailed to you from WMS and share it with us. Then will review the workshop and get back to you.

**Comment by paulparkinson** [comment]
sent, thanks @anooshapilli

**Comment by anooshapilli** [comment]
Thank @paulparkinson! I could not access the workshop URLs to review. Could you update development URLs in WMS for the workshops to review?

**Comment by paulparkinson** [comment]
@anooshapilli done, it's https://paulparkinson.github.io/learning-library/developer-library/microservices-unified-observability/workshops/freetier   thanks!

**Comment by anooshapilli** [comment]
@paulparkinson - Thanks for the link. I have mailed you the changes to the workshop ID - 6021. Once you confirm the changes requested are complete, I will start reviewing the workshop again and if everything looks good, I can work on moving it to production. Thanks!

**Comment by paulparkinson** [comment]
@anooshapilli fixed issues and set status of workshop in WMS to Self QA Complete

**Comment by anooshapilli** [comment]
@paulparkinson - Will start reviewing the changes.

**Comment by anooshapilli** [comment]
Hi @paulparkinson , Thanks for making the previous changes. Please make these final changes will approve the PR.
- Make proceed to the next lab in You may now proceed to the next lab bolded
- Number the instructions in tasks 1,7,8 in Lab 1, Lab 2 task 2
- Lab 3 - Add You may now proceed to the next lab

**Comment by paulparkinson** [comment]
changes made, thanks @anooshapilli

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
