### PR TITLE
WMS ID: 7321 Getting started with MySQL-HeatWave and feel the difference.

### PR DESCRIPTION
**Pull request by jitender-git**
This Workshop provides step-by-step instructions on how to create MySQL Database system with HeatWave cluster enabled. And execute SQL queries to experience difference in performance and execution time. With the help of this workshop customer can do hand-on Lab and witness performance. 

This workshop is approved.

### CODE REVIEW

**Review by rfontcha — CHANGES_REQUESTED** [review]
Please revert any changes to common documents and CODEOWNERS. This is likely due to the fact that you submitted the PR without first syncing your local repo with Prod. Perform "merge into current branch" and select upstream/master

**Comment by jitender-git** [comment]
Hi Rene,

I have followed the steps you have provided, Kindly review again and let me know.

Thanks,
Jitender

**Comment by rfontcha** [comment]
Your action didn't address the issue. Your PR is bringing back changes that were made in Production weeks ago. If you're unable to sync up to the current production branch the PR will be closed so you can refresh your local repo first and resubmit

**Comment by rfontcha** [comment]
@jitender-git  Closing this request as per our conversation. Connect with @ashisharyan1993 or @meghana-banka to address the issues

**Pull request closed without merging**
