### PR TITLE
feature-types-for-data-exploration-and-validation 

### PR DESCRIPTION
**Pull request by johnpeach**
* Fix issues with notebook session instructions being out of date.
* Move common images to a common folder.

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi John! 
Please make the following changes, so that the workshop follows all LiveLabs standards:
1. For each image, please include its alternative text for accessibility;
2. Please blur out your root tenancy's name in screenshots for security compliance.
Thanks!

**Comment by johnpeach** [comment]
> Hi John! Please make the following changes, so that the workshop follows all LiveLabs standards:
> 
> 1. For each image, please include its alternative text for accessibility;
> 2. Please blur out your root tenancy's name in screenshots for security compliance.
>    Thanks!

I have done this for the feature-type course, which is the one that I am working on. The alt text that you are talking about is for a course that I do not own. Can you work with the owner to get the images and alt text into compliance? The changes that I made in the course were part of moving common content from different courses into one folder. It was all linked back to a different course, which is not a good design.

**Review by arabellayao — COMMENTED** [review]
Hi John! It seems like you added some images that contain the root tenancy name (arabella). If so, could you please blur them out? Thank you!

**Comment by johnpeach** [comment]
@arabellayao I have blocked out the root tenancy images.

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Pull request merged**
