### PR TITLE
DR RackWare Lab Addition

### PR DESCRIPTION
**Pull request by bullockw**
Hi,

Creating a pull request to merge my changes for LiveLabs workshop ID 3080 - "Disaster Recovery RackWare Deployment on OCI"

Thanks!

### CODE REVIEW

**Review by kaymalcolm — APPROVED** [review]
Looks good!

**Comment by kaymalcolm** [comment]
Looks like there's a conflicting file.   oci-library/oci-hol/resource-manager/resource-manager/images/CloudShell.png

**Comment by bullockw** [comment]
Huh, I don't use that file in my lab at all so I'm not sure where it came from. How do I go about resolving?

**Comment by kaymalcolm** [comment]
Just chatted with Flavio Pereira on slack. It's one of his, he will have to help you.  It's related to a change he made.

**Review by flavio-santino — APPROVED** [review]

**Comment by flavio-santino** [comment]
I need to close this pull request and then fix the image. You will have so submit your pull request again once it is fixed. Looks like your PR touched the file and I am not sure how..

**Comment by bullockw** [comment]
Thanks Falvio. Will you let me know when the image is fixed, so I can submit the pull request again?

**Pull request closed without merging**
