### PR TITLE
ID#9281 - New livelabs workshop

### PR DESCRIPTION
**Pull request by suremoha**
I have created a new livelabs workshop on backup and recovery for Oracle Database 21c. Request you to approve.
Thanks,
Suresh

### CODE REVIEW

**Comment by manish-garodia** [comment]
Hi @anooshapilli, 
We are not production-ready yet. This is the first draft of the workshop being uploaded to the learning library. Self QA will be the next step. 
For now, we need an approval of the PR so that the workshop gets placed on the master. 
Thanks, Manish

**Comment by anooshapilli** [comment]
QA Verification in progress

**Comment by anooshapilli** [comment]
Hi @suremoha - Just following up on this PR. Could you confirm the requested changes are made to the workshop?

**Comment by suremoha** [comment]
Hi @anooshapilli ,
Thank you for your feedback. I have made the required changes to the workshop. Request you to approve the PR.

**Review by kamryn-v — APPROVED** [review]

**Pull request merged**
