### PR TITLE
New Workshop - ExaCS for Modern Data Warehouse Sales Play

### PR DESCRIPTION
**Pull request by jessrein**
Will be submitting to LiveLabs once this is approved! High priority for our team's demand gen initiative.

### CODE REVIEW

**Review by kaymalcolm — CHANGES_REQUESTED** [review]
Hi Jess, what's the workshop ID?

**Comment by jessrein** [comment]
I haven't submitted it to live labs yet so I don't have an ID yet! I thought I had to move it into this repo first

**Comment by kaymalcolm** [comment]
We can't accept pull requests without an approved workshop.  We need to ensure the Exa CS team is aware of this.  Please submit it.  They can review and turn it around quickly.

**Comment by jessrein** [comment]
Sure, I just thought I had to add the source github link when submitting a new workshop on Live Labs, but I guess I'll go ahead and submit it without it. I'm working with the team on this who built the original ExaCS labs and they are aware of the initiative.

**Review by kaymalcolm — APPROVED** [review]

**Review by kaymalcolm — APPROVED** [review]

**Pull request merged**
