### PR TITLE
Micronaut updates

### PR DESCRIPTION
**Pull request by burtbeckwith**
- update to Micronaut 3
- minor fixes and updates
- add optional steps for using Vault to store passwords and using automatic wallet download

### CODE REVIEW

**Comment by anooshapilli** [comment]
@burtbeckwith Could you update the PR with the workshop ID?

**Comment by burtbeckwith** [comment]
I'm not sure what the ID is but this is for https://github.com/oracle/learning-library/tree/master/developer-library/micronaut-oci-atp

**Comment by graemerocher** [comment]
Workshop ID is 667

**Comment by graemerocher** [comment]
I approve these changes

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
