### PR TITLE
Adding oas-workshop in  Oracle Learning Library

### PR DESCRIPTION
**Pull request by jyotsanarawat**
Rene Fontcha to work on the workshop

### CODE REVIEW

**Review by rfontcha — CHANGES_REQUESTED** [review]
Cannot be merged as you made changes to "Learning Library/Common". Please withdraw and revert those changes first.
image

**Review by rfontcha — CHANGES_REQUESTED** [review]
Please revert these two changes.

image

**Review by rfontcha — CHANGES_REQUESTED** [review]
You still have a change in the "common" library. Please revert
image

**Comment by jyotsanarawat** [comment]
Working on this.

Thanks,
Jyotsana

**Comment by rfontcha** [comment]
Jyotsana,
Just FYI, don't worry about any MD other that the one containing actual labs of the product. I'll add the following:

- Generate SSH keys
- Prepare Setup
- Environment Setup (Setup-compute)

So the only changes made by your PR should be in the library where OAS workshop resides.

**Comment by jyotsanarawat** [comment]
> Jyotsana,
> Just FYI, don't worry about any MD other that the one containing actual labs of the product. I'll add the following:
> 
> * Generate SSH keys
> * Prepare Setup
> * Environment Setup (Setup-compute)
> 
> So the only changes made by your PR should be in the library where OAS workshop resides.

**Comment by jyotsanarawat** [comment]
Hi Rene,

Reverted the last change. 
oas-workshop folder  is :
…\learning-library\analytics-library\oas-workshop 

Please check.


Thanks,
Jyotsana

**Comment by kaymalcolm** [comment]
Closing per Rene F.'s request

**Review by rfontcha — COMMENTED** [review]
@jyotsanarawat - Go ahead and re-opened. It looks clean now. Just make sure it doesn't contain any change outside of "oas-workshop"

**Pull request closed without merging**
