### PR TITLE
Fixed typos, made adjustments to alignments

### PR DESCRIPTION
**Pull request by peterrsongg**
Fixed Typos and made adjustments to the alignments of the markdown as suggested by Madu.

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
image

Please keep all the image names lower case, follow the QA checklist document on general guidelines and naming conventions

**Comment by peterrsongg** [comment]
That's so odd.. I changed the name to application.png. It is lowercased on my fork. Are you still seeing uppercased on your end?

**Comment by peterrsongg** [comment]
Screen Shot 2022-04-28 at 10 52 58 AM

On my local repository, it is lowercased. I even deleted the image and re-uploaded the image and it caught the change when I pushed it. I believe it is unable to catch changes in upper/lowercase. I'll change the name of the image itself and try again

**Comment by peterrsongg** [comment]
I've just changed the name of the file. Can you check if it's changed on your end?

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Pull request merged**
