### PR TITLE
Updated the whole workshop for graph server and client 20.4

### PR DESCRIPTION
**Pull request by ryotayamanaka**
- Replaced the screenshots and highlights.json
- Removed the TLS config steps unnecessary anymore
- Modified JDBC URL description
- Changed JShell to Python for running CREATE PROPERTY GRAPH

### CODE REVIEW

**Comment by ryotayamanaka** [comment]
Need a review by @jayant62

**Comment by kaymalcolm** [comment]
Ryota, is this ready to merge? It's been 6 days.

**Comment by jayant62** [comment]
Will review it today.

Thanks
Jayant

**Comment by jayant62** [comment]
This requires multiple fixes. 
So do not merge into master. i.e. reject the PR.

Ryota,

I’ll send you details. 
Examples of some of the changes:

The text in create-graph.md mentions a Python client while the images all show the JSHELL client.

We might as well fix the typo in the file name for highlights.json since it is now updated.

Anoosha,

We need to update an existing file, named highlights.json, in the Object Store. 

Is it possible to update it and use the same PAR or will it need a new PAR?

We will email you the file separately.

Regards
Jayant

**Comment by kaymalcolm** [comment]
Closing per request.

**Pull request closed without merging**
