### PR TITLE
ID#6661 Oracle Role Intelligence (OIRI) Workshop 

### PR DESCRIPTION
**Pull request by rkeerti**
Prerequisites are updated to include the latest lab names
Updates are made to the files based on the feedback received 
Missing screenshots are added

### CODE REVIEW

**Review by tmcginn — COMMENTED** [review]
@rkeerti - First, can you update your profile with your Oracle e-mail address - this is actually required by the OGHO.
Second, please include the WMS ID (http://bit.ly/oraclewms) for this workshop - the ID is required for every PR.
Thanks, Tom

**Comment by rkeerti** [comment]
Thanks, @tmcginn 
I have updated the email address and I have also updated the workshop ID in the title of the pull request.

**Review by rfontcha — CHANGES_REQUESTED** [review]
@rkeerti - Remove sequences after Lab under *prerequisites* for all MDs. That sequence will change depending on whether you're provisioning via green button or freetier/paid

**Review by rfontcha — COMMENTED** [review]
@rkeerti - Make the *prerequisites* consistent start with:

Prerequisites
This lab assumes you have:
- A Free Tier, Paid or LiveLabs Oracle Cloud account
- SSH Private Key to access the host via SSH (_Free-tier_ and _Paid Tenants_ only)
- You have completed:
   - Lab: Generate SSH Keys (_Free-tier_ and _Paid Tenants_ only)
   - Lab: Prepare Setup (_Free-tier_ and _Paid Tenants_ only)
   - Lab: Environment Setup

For a good example, refer to "/learning-library/enterprise-manageability-library/enterprise-manager/em-job-system-automation/em-job-system-automation.md

**Comment by rkeerti** [comment]
@rfontcha 

I have made the changes as you mentioned. The sequences from the 'Prerequisites' are removed and updated  from each md file as you mentioned.

**Review by rfontcha — APPROVED** [review]

**Pull request merged**
