### PR TITLE
MySQL, Data Integration and Data Science for Marine Life

### PR DESCRIPTION
**Pull request by vmleon**

### CODE REVIEW

**Review by kamryn-v — COMMENTED** [review]
Can you please provide the LWMS ID? No PRs can be approved without a valid LWMS ID. bit.ly/oraclelwms

**Comment by vmleon** [comment]
ID#5901

**Comment by kaymalcolm** [comment]
This needs to be moved into an appropriate folder.  Please move into data-management-library/integration/mysql folder.  The folder name at the dm library level isn't approrpriate.

**Comment by vmleon** [comment]
Hi, @kaymalcolm and @kamryn-v,

I've added a new commit relocating the workshop to the correct folder structure.

Thanks for all the help!

**Comment by vmleon** [comment]
Hi @kaymalcolm and @kamryn-v , I have pushed some other commit to add Videos I have created for the different labs. 

I would also like to add an intro video on the home page of the workshop if possible. This is the link: https://youtu.be/o51O6talZhY

Thanks a million!

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
