### PR TITLE
7241:Getting started with Oracle Cloud Infrastructure Security Advisor

### PR DESCRIPTION
**Pull request by srrahane**
Hi Team,

My workshop is already approved and I have committed the changes. Please approve.

Thanks,
Sanjay Rahane
+91 9270117692

### CODE REVIEW

**Comment by rfontcha** [comment]
@srrahane Please revert any changes made to CODEOWNERS

**Comment by srrahane** [comment]
@rfontcha there is no code changes done to CODEOWENRS from my end. Kindly help to understand more on it.

**Review by rfontcha — CHANGES_REQUESTED** [review]
Beside the change to CODEOWNERS (see attached) you have several conflicts that should be resolved before this can be approved and merged. Please do the following:

1. Sync your local repo with prod (Merge into current branch and select Upstream/Master)
2. Resolve any conflict shown
3. Commit and push to stage

image

**Comment by srrahane** [comment]
Sure, checking on the steps provided.

**Comment by rfontcha** [comment]
You're also making changes to 3,863 files including many files from many libraries, common files, and others. Closing the PR. Please follow  the steps I provided earlier and verify that you're only making changes to your workshop folder before re-submitting

**Pull request closed without merging**
