### PR TITLE
Init Deployment of FPP Tutorials

### PR DESCRIPTION
**Pull request by DaveL-Tex**
Thanks Kay.

### CODE REVIEW

**Review by tmcginn — CHANGES_REQUESTED** [review]
Dave,
Couple of things:
1) you need to remove the shell scripts per Oracle GitHub Organization (OGHO)
2) Shouldn't this workshop be under the data-management?

**Comment by kaymalcolm** [comment]
Hi Dave, haven't heard back from you.  Should we close this pull request?

**Comment by DaveL-Tex** [comment]
Hi,

 

No, I’ve been too busy to get back to this.  Hopefully I can chat w/ y’all in the morning.

Dave

**Comment by kaymalcolm** [comment]
Dave requested closure.

**Pull request closed without merging**
