### PR TITLE
Added MDS Lab to OCI Lift & Shift Workshop

### PR DESCRIPTION
**Pull request by RajOracleTest**
add lab 3 - on how to connect mds with oscommerce application
Updated few expired links

### CODE REVIEW

**Review by kaymalcolm — CHANGES_REQUESTED** [review]
This contains updates to common files that aren't allowed.  You cannot change the default README.  Please send your staging site so we can review and explain why you made these edits before allowing these changes.  This merge is blocked.

**Comment by RajOracleTest** [comment]
Hi Kay,

I have added new lab to existing OCI Move and Improve Workshop.
New lab 3 – Connecting application with MDS.

My Staging Site:
https://rajoracletest.github.io/learning-library/solutions-library/oci-move-improve/workshops/freetier/index.html?lab=introduction#Introduction

Regards,
Raj Rawool

**Comment by kaymalcolm** [comment]
Understood.  You inadvertently changed key files in the repo.  So we cannot merge this.  Please contact Kamryn V. or Anoosa P tomorrow to resolve.

**Review by kaymalcolm — CHANGES_REQUESTED** [review]
This has changes that are erroneous made to some of LiveLabs' key files.  Cannot allow this PR to move forward.  Please attend office hours. https://confluence.oraclecorp.com/confluence/display/DCS/Workshop+Modernization+Project#WorkshopModernizationProject-OfficeHours

**Comment by RajOracleTest** [comment]
Hi Kay,
You can close this PR.
I'm working with Anoosha to fix this issue and will send new PR.

Thanks,
Raj Rawool

**Pull request closed without merging**
