### PR TITLE
Template updated for OML labs

### PR DESCRIPTION
**Pull request by MoitreyeeHazarika**
Templates and screenshots updated for OML labs.

### CODE REVIEW

**Review by tmcginn — COMMENTED** [review]
Please add the WMS ID - we won't approve a pull request without the id.

**Comment by MoitreyeeHazarika** [comment]
> 
> 
> Please add the WMS ID - we won't approve a pull request without the id.

Hi Tom @tmcginn ,

I do not have the workshop ID as yet as they have been migrated from OBE template to LiveLabs tutorials currently. I have just updated the latest LiveLabs template. I'll initiate the workshop creation process once the tutorials are in GitHub.

Thanks
Moitreyee

**Comment by tmcginn** [comment]
Hi @MoitreyeeHazarika -

You need to follow the process please. Create the entry in the WMS and then add the ID of the entry to this PR.  Thank you for your understanding.

Tom

**Comment by tmcginn** [comment]
@MoitreyeeHazarika - have you created the WMS entry yet? If you are waiting until you have all the changes in, please just push the changes to your fork rather than adding pull requests. If you plan to wait, I'll close this PR until you are ready with the WMS ID.

**Comment by MoitreyeeHazarika** [comment]
Hi @tmcginn , I have pushed the updates to my forked library. I am in the process of creating the WMS request, but got stuck in answering some questions related to the green button. I am waiting for the PM to respond to some of those questions in the Green Button questionnaire (you are also marked in that email). If it is a deviation from the process (a long wait), you may go ahead and close this PR. I'll create a new PR when I have those inputs handy. 

Thanks

**Comment by tmcginn** [comment]
Thanks @MoitreyeeHazarika - feel free to make the PR again when you have the WMS ID.

**Pull request closed without merging**
