### PR TITLE
LWMS ID 5761: Added Bastion Lab processing to workshop

### PR DESCRIPTION
**Pull request by plforacle**
LWMS ID 5761: Added Bastion Lab processing to workshop

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
Please give valid and descriptive image names, and all images need to have alt text.  refer QA checklist document for general guidelines
image

**Comment by plforacle** [comment]
Madhusudhan,
This workshop was approved and moved to production 2 months ago. Now you are asking me to change at least 30 images and text. It will take days to complete this request, and my workshop is today. Is there an easier solution?

Thank you,
Perside Foster | MySQL Senior Partners Solution Engineer
email: ***@***.******@***.***>
phone: 1.786.877.9063
Oracle  Florida

From: Madhusudhan Rao ***@***.***>
Sent: Thursday, May 5, 2022 12:38 AM
To: oracle/learning-library ***@***.***>
Cc: Perside Foster ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [oracle/learning-library] LWMS ID 5761: Added Bastion Lab processing to workshop (PR #4994)


Please give valid and descriptive image names, and all images need to have alt text. refer QA checklist document for general guidelines
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/70625227/166864217-fff66586-6cce-46ad-a78d-2cc32eed6fe7.png__;!!ACWV5N9M2RV99hQ!MMX_tCejSWd9PXJMitsCIsPX5qU1YGUqGtwoubhYzCCTZSLzTzYMaqWTG-qlz1AzYcBpZH7se2SBfxeZ5A_P8DDWtVi5$>

**Comment by madhusudhanrao-ppm** [comment]
Please refer QA checklist document, and filenames should not have capital letters or underscores,  these are part of accessibility requirements and workshop best practices. 

image

**Comment by kaymalcolm** [comment]
Closing this due to age of PR.  Please send a new one after your repo is sync'd.

**Pull request closed without merging**
