### PR TITLE
WMS ID: 11045 - Creating "[Japanese] Launch GraalVM to accelerate java workload"

### PR DESCRIPTION
**Pull request by junssuzuki**
Creating new workshop. This workshop will be used as hands-on lab on the event of [Oracle Japan Developer Days 2022 spring](https://developer.oracle.com/jp/developer-days-2022-may/) scheduled on 27th May.

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
Please give descriptive image names, refer QA checklist document, and mask the name of other workshops like OML4Py in the workshop documentation. All images should have alt text associated image names

image

**Comment by madhusudhanrao-ppm** [comment]
1.4.	Filenames should be descriptive, not step numbers, not autogenerated names (QA checklist document) and all images should have alt text. Please remove image files which are not used in the markdown.  

image

**Comment by madhusudhanrao-ppm** [comment]
1.4.	Filenames should be descriptive, not step numbers, not autogenerated names (QA checklist document) and all images should have alt text. Please remove image files which are not used in the markdown.  

image

**Review by anooshapilli — APPROVED** [review]

**Review by kaymalcolm — APPROVED** [review]
Approving.  Anoosha working with Jun.

**Pull request merged**
