### PR TITLE
UI changes

### PR DESCRIPTION
**Pull request by Mmm-Biscuits**

### CODE REVIEW

**Comment by Mmm-Biscuits** [comment]
i cant seem to resolve these conflicts

**Review by anooshapilli — DISMISSED** [review]

**Comment by anooshapilli** [comment]
@Mmm-Biscuits, Please resolve the conflicts

**Comment by Mmm-Biscuits** [comment]
i cant seem to resolve these conflicts

**Comment by Mmm-Biscuits** [comment]
There is no way to view what is conflicting

**Comment by Mmm-Biscuits** [comment]
ive removed the 2 files to fix the conflict...once we get this PR done, ill push and create another PR with those 2 files

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
