### PR TITLE
OCI Library - configuring auto scaling updates

### PR DESCRIPTION
**Pull request by yaisah**
Added workshop folder for OCI Library. Made updates to the Configuring Auto Scaling folder.

### CODE REVIEW

**Comment by umairs123** [comment]
Hello
 Can you please provide some more details on what changes were made to Auto scaling lab. I did a review though couldnt tell what changes were made ? 
thanks

**Comment by umairs123** [comment]
Actually i see the differences
I am hesitant to accept these changes as Qloudable platform requires specific markup (* vs ** etc) and it can throw off the formatting when the lab is launched and content is pulled.
For images we can not specify a path like ./../ it must be the absolute path to the main Git hub directory.
Have you received complaints or tried out the lab to determine that content is not appearing appropriately ?
thanks

**Comment by umairs123** [comment]
please let us know on previous comments and we can reopen it.
thanks

**Comment by yaisah** [comment]
Hello, apologies for not giving enough context. This request is not for qloudable. This is a new folder I created called "OCI-HOL" where we will be able to test our own platform using "LIVELABS" instead of qloudable. I had a meeting on Friday with Kay Malcolm, Larry Beausoleil, and Flavio Pereira with a walk-through of the new format. If you have any questions please feel free to reach out to me or Kay Malcolm. 

Upon approval of the pull request, you should be able to see the hands on lab following the below link: https://oracle.github.io/learning-library/oci-library/oci-hol/freetier/index.html?lab=lab-2-configuring-auto-scaling  

This folder includes the changes requested for this pull request. 
image


This is how the hands on lab should look after the pull request is complete (again, not in qloudable but in LIVELABS).

image

**Comment by umairs123** [comment]
approving since this is a new folder with labs for Live Labs platform

**Pull request merged**
