### PR TITLE
edits after QA review

### PR DESCRIPTION
**Pull request by OanaTurnea**
Thank you very much!

### CODE REVIEW

**Comment by klazarz** [comment]
Hi Oana, could you please add the WMS#ID and have a look at the conflicts shown in GitHub for your PR? Thanks

**Comment by OanaTurnea** [comment]
Hello,

WMS ID#7161 
Resolving files.
Thank you!

**Comment by OanaTurnea** [comment]
Hi!
Could you check if it's ok, now?
Thank you!

**Review by klazarz — APPROVED** [review]

**Comment by OanaTurnea** [comment]
Thank you very much!

**Pull request merged**
