### PR TITLE
Workshop (ID# 7041) Re-arranged folders & other changes discussed in Office Hours

### PR DESCRIPTION
**Pull request by manish-garodia**
Hello,

I have modified the workshops and labs as discussed in the Office Hours.

Following are the modifications -

Moved 'prepare-setup' inside the install-db folder

Removed the common file and inserted the note inside Introduction

Changed the folder name from main to desktop

Removed 'initialize-environment' from desktop

Moved the introduction lab first followed by 'get started' in all manifests

Changed the heading 1 of Introduction to 'Oracle Database 21c Installation'

Added if condition to Introduction to exclude sections from the parent workshop.

Changed the folder names from freetier, livelabs, desktop to freetier-install-db, livelabs-install-db, desktop-install-db

Besides, I performed Self QA for the workshop and ran through the lint checker on all labs again.

Request for approval please.  Thank you
~MG

### CODE REVIEW

**Review by tmcginn — APPROVED** [review]

**Review by tmcginn — COMMENTED** [review]
@manish-garodia - you have conflicts in this PR that must be resolved before I can approve it

Conflicting files
data-management-library/database/21c/fundamentals/dba-essentials/install-db/workshops/freetier/manifest.json
data-management-library/database/21c/fundamentals/dba-essentials/prepare-setup/prepare-setup.md

One other thing - I see you are using the include: function, but we are no longer supporting that for forward compatibility with OHC/Learn.

**Comment by manish-garodia** [comment]
Hello @tmcginn,
I thought I removed this file -
data-management-library/database/21c/fundamentals/dba-essentials/prepare-setup/prepare-setup.md

Because the preppare-setup.md file is modified and moved under -
data-management-library/database/21c/fundamentals/dba-essentials/install-db/prepare-setup/

Also, the folders Freetier, main, and livelabs are renamed as freetier-install-db, desktop-install-db, and livelabs-install-db.

Would be great if you please guide if anything else is missing.

**Comment by manish-garodia** [comment]
Also, I will remove all include files and submit PR once again. Thank you

**Comment by manish-garodia** [comment]
Hello @tmcginn,

I have modified the labs as suggested. 

Fixed the conflicts in these files: freetier-install-db/manifest.json and prepare-setup.md. No more conflicts. 
Removed the common files
Removed the include function from all occurrences
Other minor changes

Besides, I performed Self QA for the workshop and ran through the lint checker on all labs again.

Please verify and approve the pull request if all ok. We are eager on getting the workshop released into production. Your help is greatly appreciated. 

Thank you
~MG

**Review by tmcginn — APPROVED** [review]
Awesome @manish-garodia !

Thank you, Tom

**Pull request merged**
