### PR TITLE
Additions to workshop id #8281

### PR DESCRIPTION
**Pull request by SimonWeisserOracle**
Changes made to workshop id #8281

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
Please refer QA checklist document. 
Section 1.4. Filenames should be descriptive, not step numbers, not autogenerated names
Section 4.7  Please use Alt text for images to describe what the image is. Refer QA checklist document

**Comment by SimonWeisserOracle** [comment]
Can you please be more specific? I have followed the QA checklist, and had gotten feedback from Arabella Yao who is part of the LiveLabs team and had made corrections based on this feedback.

**Comment by madhusudhanrao-ppm** [comment]
some of the image names like img3  img7  img8 newimage1 newimage2 etc are not valid names and also there needs to be an Alt text within the image tag in the markdown describing what the image is from an accessibility perspective

**Comment by SimonWeisserOracle** [comment]
Changes made to lab 8821, please review.

**Comment by madhusudhanrao-ppm** [comment]
This branch has conflicts that must be resolved

**Comment by SimonWeisserOracle** [comment]
How do I go about resolving these conflicts? I am not sure why this exists

**Comment by madhusudhanrao-ppm** [comment]
1. Keep a local backup of the work that you have already done, just in case files get overwritten
2. from the GitHub Desktop, Select Merge into Current Branch, upstream/master 
3. Push the changes to your repository with "Push Origin." 
4. Verify your repo for all the changes that you had made. If it is available there 
5. Then create a PR, ( Please go through "Get Started with Git and Set up the GitHub Environment" LiveLabs guide) 
also, join one of the LiveLabs Office hours if you have any specific questions

**Comment by SimonWeisserOracle** [comment]
Conflicts resolved please review

**Comment by madhusudhanrao-ppm** [comment]
This branch has conflicts that must be resolved
data-management-library/database/text/full-text-indexing/introduction/introduction.md
data-management-library/database/text/full-text-indexing/maintenance/maintenance.md
data-management-library/database/text/full-text-indexing/queries/queries.md
sample-livelabs-templates/create-labs/labs/livelabs-faq/livelabs-faq.md

**Comment by kaymalcolm** [comment]
Closing due to conflicts and age.

**Pull request closed without merging**
