### PR TITLE
Minor style updates for OHC WMS ID is 442

### PR DESCRIPTION
**Pull request by ljamen**
Lab was created for Live Labs and needed some minor updates to meet OHC standards. 

PLEASE NOTE: I am not sure how/why the data-management-library/sharding/eshop/images deletions ended up in my PR. I did not intend to delete them (they are not my files.) It had a while since I refreshed my repo and I'm assuming these were just lingering from a previous sync. Please let me know if there is something I need to address here.

### CODE REVIEW

**Comment by klazarz** [comment]
Hi @ljamen, could you please add the WMS ID? Thanks.

**Comment by ljamen** [comment]
WMS ID is 442

**Comment by ljamen** [comment]
Is there something else I need to provide here?

**Comment by klazarz** [comment]
@ljamen  Thanks. Ill ping on Slack regarding those images - we need to fix that

**Comment by klazarz** [comment]
@ljamen i will close this PR and will work with you to fix things on your end and create a new PR

**Pull request closed without merging**
