### PR TITLE
#5141 Oracle -sharding on Docker 

### PR DESCRIPTION
**Pull request by ashisharyan1993**
move the workshop folder to learning-library/data-management-library/sharding

### CODE REVIEW

**Review by rfontcha — APPROVED** [review]

**Review by tmcginn — CHANGES_REQUESTED** [review]
@ashisharyan1993 - can you confirm why you are deleting a manifest file in a completely different directory from the primary one in this PR:

developer-library/converged-db/oracle-sharding/workshops/livelabs/manifest.json

**Comment by ashisharyan1993** [comment]
Hi @tmcginn,

It's a sharding workshop. According to that, it's not come under the converged DB folder as suggested by @kaymalcolm and @rfontcha.

so I moved the complete workshop folder to "learning-library/data-management-library/sharding"

and I will inform the same to workshop owner.

**Comment by tmcginn** [comment]
@ashisharyan1993
>> so I moved the complete workshop folder to "learning-library/data-management-library/sharding"
That part is fine, I am concerned about a file being deleted in this PR:
    developer-library/converged-db/oracle-sharding/workshops/livelabs/manifest.json
I don't think you intended to delete this file and it belongs to a different workshop, right?

**Comment by ashisharyan1993** [comment]
Hi @tmcginn ,

The above mention file "**developer-library/converged-db/oracle-sharding/workshops/livelabs/manifest.json**" 
is part of this workshop only and the content  is not required as i have created new mainfest. 

So I can say, it will not effect any other workshop.

**Comment by tmcginn** [comment]
@ashisharyan1993 - thanks for the confirmation

**Review by tmcginn — APPROVED** [review]

**Pull request merged**
