### PR TITLE
ords in oci lab

### PR DESCRIPTION
**Pull request by Mmm-Biscuits**

### CODE REVIEW

**Comment by anooshapilli** [comment]
@Mmm-Biscuits Could you share the workshop ID?

**Comment by Mmm-Biscuits** [comment]
6361

**Comment by Mmm-Biscuits** [comment]
we also need 2 zips hosted for this

**Review by kaymalcolm — APPROVED** [review]
Approved.  Contact livelabs-help-db_us@oracle.com for the object storage request

**Pull request merged**
