### PR TITLE
new need help section

### PR DESCRIPTION
**Pull request by oegentil**

### CODE REVIEW

**Review by tmcginn — COMMENTED** [review]
Hi Orlando,
I think you are missing an element in your manifest.json files that includes the e-mail address where the Need Help? goes. For example, for database we use:

help": "livelabs-help-db_us@oracle.com",

This goes between the "workshoptitle" and "tutorials" elements at the top.

**Comment by tmcginn** [comment]
Talk to @yunyidi-han if you have questions

**Review by anooshapilli — DISMISSED** [review]

**Comment by yunyidi-han** [comment]
@oegentil Hey Orlando, these support template changes in oci-library/oci-hol/oci-hpc* need to be reverted, they belong to HPC (Chris Iwicki). Alternatively, in your local repository, do a merge from upstream/master and accept all incoming changes for conflicted OCI-HPC files and ensure none of the files in oci-hpc say modified.

**Comment by tmcginn** [comment]
Hey Orlando, it looks like there are conflicts in your PR....

**Comment by oegentil** [comment]
conflicts fixed and help element included

**Review by tmcginn — APPROVED** [review]

**Pull request merged**
