### PR TITLE
WMS ID:9821 - Perform Sentiment Analysis with OCI AI Language Service and OAC

### PR DESCRIPTION
**Pull request by cjarimani**
It's a new workshop and I'm following the QA Checklist document.

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
please give descriptive image names and all images should have alt text, refer QA checklist document for general workshop guidelines 

image

**Review by AndQui — COMMENTED** [review]
labs 5 and 6 have image titles with underscores - please change to dashes

**Comment by cjarimani** [comment]
Updated the images in lab5 and lab6

**Review by AndQui — COMMENTED** [review]
Please change oac_banner.png in lab 6 - all other changes are good.

**Comment by cjarimani** [comment]
Updated.

**Review by AndQui — COMMENTED** [review]
All changes look good.

**Review by malcherm — APPROVED** [review]

**Pull request merged**
