### PR TITLE
DBSec Livelabs-v1 (Final Version)

### PR DESCRIPTION
**Pull request by hloumi**
Hi,

Here are the final versions of the 2 DB Security livelabs : Baseline and Advanced.

I reviewed 100% of the labs and normally everything is ready  to go in production :-)

Best regards
Hakim

### CODE REVIEW

**Review by kaymalcolm — CHANGES_REQUESTED** [review]
Hakim, please chat with Rene about this request.  Please sync and merge your repository with the latest code.  We moved See an Issue to Need Help and your changes overwrote those changes.

**Review by kaymalcolm — COMMENTED** [review]
Also, <br> and other html tags are not permitted.  They mess up the rendering engine.  Noticed some html tags in the markdown.

**Comment by hloumi** [comment]
Making few more changes

**Comment by hloumi** [comment]
Making few more changes and I'll submit my PR

**Pull request closed without merging**
