### PR TITLE
Need Help updates for the 19 workshops in "Free Tier Complete" status

### PR DESCRIPTION
**Pull request by yunyidi-han**
All workshop changes are grouped into their respective commits.

There is a commit that was reverted twice (DB Security - Native Network Encryption), I had tried to edit the commit message since it also included Need Help updates for the DB Security - Privilege Analysis workshop. 

The bulk of this was done with VSC's "Find in Folder" function for each individual workshop folder and manually checking the count of replaced instances, and then verifying website functionality through LiveServer.

Some of the workshops also have paths to Markdown files in the "common" folder/path (the "Prerequisite" file being a predominant one), and I've left those unchanged at the moment following guidance from Kamryn. 

Just want to note that there was quite a lot of intermingled use of two spaces vs tabs in the manifest files, syntax-wise. I'm rooting for tabs as our syntax standard :)

### CODE REVIEW

**Review by tmcginn — CHANGES_REQUESTED** [review]
Didi,
I don't think these manifest.json changes will work.

What you have now:
{
    "workshoptitle": "Database 21c on Autonomous Database",
    "tutorials": [
    "help": "LIVELABS-HELP-DB_US@ORACLE.COM",
	"tutorials": [

What is required:

{
    "workshoptitle": "Database 21c on Autonomous Database",
    "help": "LIVELABS-HELP-DB_US@ORACLE.COM",
    "tutorials": [

Two changes: 
1) The "help" element is outside of the "tutorials":[ array
2) there is only one array with "tutorials":[

Please have Kamryn and/or Anoosha show you how to double check that your changes work using Atom or VSC.

**Comment by tmcginn** [comment]
BTW, I checked https://github.com/oracle/learning-library/pull/2676, and you did do that one correctly.

**Comment by yunyidi-han** [comment]
Roger. I'll double check and change them, sorry about that.

**Comment by yunyidi-han** [comment]
GitHub syntax


Tom, 

After double checking and consulting with Kamyrn, I believe my current PR is correct.

When I made the changes on this PR (as opposed to #2676) for the manifest.json, I deleted the line instead of just inserting the additional line.  Git interrupted it as a line deletion, which is where I think is the source of this confusion.

If you see the attached image which is a snip of the problem you mentioned, the first "tutorials": [ is deleted as denoted by the red line and the minus symbol in front of it, and then the other two lines are added.

Let me know if I'm in the wrong here, thanks!

**Review by tmcginn — APPROVED** [review]
Didi, 
You're right! My mistake, I read the deletion and addition as one complete change.
Tom

**Pull request merged**
