### PR TITLE
ID#6041 - Oracle Data Integrator Web Edition - Intro to Data Transforms

### PR DESCRIPTION
**Pull request by JayantMahto**
This workshop provides step-by-step guide to deploy ODI Web Edition from OCI Marketplace and instructions on how to use Data Transforms to create data integration project.

### CODE REVIEW

**Review by davidastart — APPROVED** [review]

**Review by davidastart — COMMENTED** [review]
Anoosha is working with Jayant on this and is pending approval.

**Review by davidastart — CHANGES_REQUESTED** [review]
@JayantMahto please work with Anoosha on the changes.

**Comment by JayantMahto** [comment]
Moved odi-web-edition-datatransforms to odi folder
changed the folder name to all lower case
removed deploying/Files folder

**Review by anooshapilli — APPROVED** [review]

**Review by davidastart — APPROVED** [review]
Approved based on Anoosha's feedback.

**Pull request merged**
