### PR TITLE
Geolocation Enrichment of Log Data with Logging Analytics

### PR DESCRIPTION
**Pull request by smiraj99**
Workshop ID# 9521 

Description: 
Enrich logs with geolocation data for deeper analysis and identifying spatial patterns
Learn how to add geolocation data automatically to public and private IPs in your logs

### CODE REVIEW

**Review by klazarz — DISMISSED** [review]
Hi @smiraj99 ,
in enterprise-manageability-library/logging-analytics/geolocation-enrichment/analytics/analytics.md it it says 'Estimated Lab time: 10 documentation' - Can you fix that typo please?

Also, in enterprise-manageability-library/logging-analytics/geolocation-enrichment/private-ip/private-ip.md, can you please obfuscate/anonymize any IP-addresses?

thanks,
Kevin

**Comment by smiraj99** [comment]
> Hi @smiraj99 , in enterprise-manageability-library/logging-analytics/geolocation-enrichment/analytics/analytics.md it it says 'Estimated Lab time: 10 documentation' - Can you fix that typo please?
> 
> Also, in enterprise-manageability-library/logging-analytics/geolocation-enrichment/private-ip/private-ip.md, can you please obfuscate/anonymize any IP-addresses?
> 
> thanks, Kevin

Hi Kevin,

Thanks for reviewing my txn.
I have updated the Estimated Lab time typo

Regarding IP addresses, I copied them from internet, they are not part of company Infrastructure and used only for demo purpose.
Also, since this feature mainly focuses on IP Addresses, I thought of not obfuscating them.
Is it ok to keep them else I will obfuscate.

**Comment by malcherm** [comment]
We will need them at least partially obfuscated. Understanding that these are part of the security process, even if not internal to Oracle or defaults, the reviews will just catch plain text for IPs and such.
Thanks!

**Review by malcherm — APPROVED** [review]
The public IPs are part of the data sets and needed examples because this is what the lab actually demonstrates. These are random public IP addresses and are part of a public data set, not specific to Oracle.

**Review by malcherm — APPROVED** [review]

**Pull request merged**
