### PR TITLE
WMS ID#11089  Get Started with Oracle Integration

### PR DESCRIPTION
**Pull request by kkatta11**
PR for new workshop Get Started with Oracle Integration
#WMS Id: 11089

### CODE REVIEW

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Comment by madhusudhanrao-ppm** [comment]
This branch has conflicts that must be resolved
Conflicting files
oic-integration-library/experiential/erpcloud-business-event/setup/images/paste-run-sql-script.png

**Review by rfontcha — CHANGES_REQUESTED** [review]
@kkatta11 - All files and path should be in lowercase. No Upper or Mixed cases, including file extensions. Please rename, commit, and push. [Follow these instructions](https://objectstorage.us-ashburn-1.oraclecloud.com/p/JkBnGwHa1L4YqDxrA2TDpy3JX0RcErwQ-xH-lRkEtmNB5D_GRrnThZ89rEp4DyaY/n/natdsecurity/b/misc/o/github-fix-char-cases.txt) to address the issue

Below is just a sample. There are many more and the instructions above should address it in a single run!
image

**Comment by kkatta11** [comment]
@rfontcha live lab content in the folder oic-integration-library\core-competencies\insight is still a work in progress by my colleague @lccortez . Hence the issues.

**Comment by rfontcha** [comment]
@kkatta11  - Understood but those issues noted cannot be brought into prod and must be resolved before this PR can be merged

**Comment by chablani** [comment]
I have completed fixes to `oic-integration-library/common/adb-provision`.

**Review by rfontcha — CHANGES_REQUESTED** [review]
@kkatta11 - Please rename this and any other file you might have missed to lowercase.
image

**Comment by kkatta11** [comment]
@rfontcha the file name is fixed. Can you please process the PR.

**Comment by kkatta11** [comment]
@madhusudhanrao-ppm can you approve the merge?

**Review by malcherm — APPROVED** [review]

**Pull request merged**
