### PR TITLE
(#11060) Created New Workshop Manage user accounts and security

### PR DESCRIPTION
**Pull request by manish-garodia**
Hello,
Developed a new workshop on Manage user accounts and sceurity for Oracle Database 21c, WMS ID is #11060.
Please approve the PR. Thank you
~MG

### CODE REVIEW

**Comment by anooshapilli** [comment]
Hi @manish-garodia, As this is a new workshop, please submit the filled out  Self QA document to livelabs-help-db_us@oracle.com mailbox to review. If everything looks good we will approve the PR.

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Comment by manish-garodia** [comment]
Hi @anooshapilli,
This workshop belongs to the EM/OMC council. Can you please confirm to which mailbox to send the QA document?

**Comment by malcherm** [comment]
The EM email is livelabs-help-em_us@oracle.com but both or either one would still get the QA checklist reviewed.

**Comment by manish-garodia** [comment]
During QA of an earlier workshop, Steven Lemme shared this mailbox for EM related labs: livelabs-help-em_us_grp@oracle.com

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Pull request merged**
